### ISSUE TITLE
Can't add a second element to the integration to watch a second printer

### ISSUE THREAD

**Issue by VstudioLAB** [nobodyguy/obico_ml_ha_integration#2]
When I try to add a second element to watch a second 3d printer, it doesn't add entities.

![image](https://github.com/user-attachments/assets/06765f4c-56c6-47cb-84df-d53301e49c79)

System infos: 
-----------------------------------------------------------
 Add-on: Obico ML
 Home Assistant addon for integrating Obico ML-based monitoring.
-----------------------------------------------------------
 Add-on version: 1.1.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.2  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.10.3
 Home Assistant Supervisor: 2024.10.2

**Comment by nobodyguy** [comment]
Hello @VstudioLAB,
setup with multiple cameras is currently not supported. You can create multiple config entries (as you did), but the data passing is global (in terms of the integration). The only reason for this decision was purely due to the effort involved.
You can track the progress in this branch - https://github.com/nobodyguy/obico_ml_ha_integration/tree/multiple_instances_support
And I'd also rather turn on multithreading support in the Obico ML Addon.

**Comment by VstudioLAB** [comment]
Hi! thank you for your fast answer!
I am not sure to understand (autism and language barrier) if i should turn on multithreading or if it's something you're working on. 
There is only an option to change the port for the server in the addon. Is there a config to change in a file?

**Comment by nobodyguy** [comment]
Sorry for my confused answer. Based on the quick log investigation I thought that the data passing didn't work with the multi-camera setup. But it turned out that the only issue is just with the unique IDs that are fixed on the branch, but I haven't been able to fully test it.
So feel free to use the branch, I'll merge it back to the main branch and publish a new version with the fix.
It should work as it is, but the server part (HA Addon) is single threaded, so there could be timeout errors when multiple instances try to access the API.
I'll update the addon part to enable multithreading with configurable number of workers/threads, but it would take some time, so I can't give you an exact time estimate right now.
